version: '3'

services:

  vnc: &vnc
    image: f1tenth-riders-vnc
    build:
      context: .
      dockerfile: compose/vnc/Dockerfile
      args: 
#        - PARENT=ros:melodic-robot-bionic
        - PARENT=ros:noetic-robot-focal
#        - ROS_DISTRO=melodic
        - ROS_DISTRO=noetic

  vnc-dev:
    <<: *vnc
    stdin_open: true
    tty: true
    ports: 
      - "6080:6080"

  roscore: &roscore
    image: f1tenth-riders-roscore
    build: 
      context: compose/roscore
      args: 
        - PARENT=f1tenth-riders-vnc
  
  roscore-dev:
    <<: *roscore
    volumes: 
      - ./compose/roscore/start.sh:/start.sh
    stdin_open: true
    ports:
      # expose ROSCORE port to Out
      - 11311:11311

  bridge: &bridge
    image: f1tenth-riders-bridge
    build:
      context: .
      dockerfile: compose/bridge/Dockerfile
      args: 
        - PARENT=f1tenth-riders-vnc

  bridge-dev:
    <<: *bridge
    stdin_open: true
    ports:
      - 6080:6080
    volumes:
      - ./f1tenth_gym_ros:/catkin_ws/src/f1tenth_gym_ros
      - ./compose/bridge/f1tenth.rviz:/f1tenth.rviz
      - ./compose/bridge/start.sh:/start.sh
    environment: 
      - ROS_MASTER_URI=http://host.docker.internal:11311
      - RACE_MAP_PATH=${RACE_MAP_PATH}
      - RACE_MAP_IMG_EXT=${RACE_MAP_IMG_EXT}
      # Scenario: 0 for single car timed trial (qualifying), 1 for dual car racing (grand prix)
      - RACE_SCENARIO=0
      - EGO_ID=icart_id
      # - OPP_ID=opp_id
      # Starting pose for both of the cars, also a map parameter
      - EGO_STARTING_X=-1.25
      - EGO_STARTING_Y=0.0
      - EGO_STARTING_THETA=1.57079633
      - OPP_STARTING_X=0.0
      - OPP_STARTING_Y=2.0
      - OPP_STARTING_THETA=1.5

  agent: &agent
    image: f1tenth-riders-agent
    build:
      context: .
      dockerfile: compose/agent/Dockerfile
      args:
        - PARENT=f1tenth-riders-roscore

  agent-dev:
    <<: *agent
    environment:
      - ROS_MASTER_URI=http://host.docker.internal:11311
      - F1TENTH_AGENT_NAME=icart_id
    volumes:
      - ./pkg:/catkin_ws/src/pkg